theme: jekyll-theme-minimal
title: [Amer Din]



description: [Scroll to learn more about m]
google_analytics: [UA-134855408-1]



--- # Favorite movies
 - Casablanca
 - North by Northwest
 - The Man Who Wasn't There

