theme: jekyll-theme-cayman
title: [Amer Din]



description: [Scroll to learn more about me]
google_analytics: [UA-134855408-1]



--- # Favorite movies
 - Casablanca
 - North by Northwest
 - The Man Who Wasn't There

